### ISSUE TITLE
node incompatible module

### ISSUE THREAD

**Issue by PinkyRabbit** [forfuturellc/mau#4]
I got the error:
```
usesa@pinkya-spot:/var/www/telegrambot$ sudo yarn add mau
yarn add v1.2.1
warning ../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error mau@0.2.0: The engine "node" is incompatible with this module. Expected version ">=7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
I installed version 0.2.0  w/o problems just want warn you. Thanks for your job!

**Comment by GochoMugo** [comment]
*Ooh, hello. It is you. :smile: Just sent you an email pointing you to this repo.*

Haven't been using `yarn` though. Which Node.js version are your using?

**Comment by PinkyRabbit** [comment]
I installed it about month ago
```
usesa@pinkya-spot:/var/www/telegrambot$ node -v
v6.11.4
```
upd. I installed mau with npm without errors and all looks fine. But _yarn_ dont want working with _mau_.

**Comment by GochoMugo** [comment]
I have defined the package as to be used with Node.js v7+.

Please upgrade your Node.js installation.
